name: CompaniesApiCI

on:
  push:
    branches:
      - main

jobs:
  docker_hub:
    runs_on: ubuntu-latest
    steps:
      uses: actions/checkout@v2
      uses: docker/build-push-action@v1
      with:
        username: ${{secrets.DOCKER_USER}}
        password: ${{secrets.DOCKER_PASSWORD}}
        repository: ${{secrets.DOCKER_USER}}/companies_api